version: '3.6'
services:

  resource-processor-service:
    image: resource-processor-service-local-image
    build:
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - resource-network

networks:
  resource-network:
    external: true
    driver: bridge