spring:

  application:
    name: resource-processor-service

  cloud:
    config:
      uri: http://service-configurations:8888

  config:
    import: optional:configserver:http://service-configurations:8888
